id: I5D737F5F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T19:49:21+00:00'
last_modified: '2022-06-08T00:52:00.401279+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC436
  title: བོད་ཀྱི་དེང་རབས་སྙན་ངག་རིག་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    C696:
      image_group_id: I2PD18299
      title: ''
      total_pages: 274
      order: 1
      base_file: C696.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
